name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.sdkmanrc'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.sdkmanrc'
      - 'README.md'

permissions:
  contents: read

jobs:
  build:
    name: "Build with ${{ matrix.version }}"
    strategy:
      matrix:
        version: [ 17 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw verify
